import tkinter
from tkinter import * #sanity check

win = Tk()
def add(): result.config(text=float(numb1.get()) + float(numb2.get()))
def sub(): result.config(text=float(numb1.get()) - float(numb2.get()))
def multiply(): result.config(text=float(numb1.get()) * float(numb2.get()))
def divide():
    try: result.config(text=float(numb1.get()) / float(numb2.get()))
    except ZeroDivisionError: result.config(text="Error: Div by 0")
def floor(): result.config(text=float(numb1.get()) // float(numb2.get()))
def power(): result.config(text=float(numb1.get()) ** float(numb2.get()))
def modulo(): result.config(text=float(numb1.get()) % float(numb2.get()))
title = Label(win, text="Python GUI: Basic Calculator", font=("Century Gothic", 20), fg="white", bg="#123740")
title.place(x=120, y=18)
fnum = Label(win, text="First Number:", font=("Century Gothic", 16), fg="white", bg="#123740")
fnum.place(x=20, y=65)
Snum = Label(win, text="Second Number:", font=("Century Gothic", 16), fg="white", bg="#123740")
Snum.place(x=20, y=100)
numb1 = Entry(win, width=17, font=("Century Gothic", 16))
numb1.place(x=230, y=70)
numb2 = Entry(win, width=17, font=("Century Gothic", 16))
numb2.place(x=230, y=100)
result = Label(win, text="Result:", font=("Century Gothic", 16), fg="white", bg="#123740")
result.place(x=460, y=65)
result = Label(win, text="", font=("Century Gothic", 16), fg="white", bg="#123740")
result.place(x=475, y=90)  
btn1 = Button(win, width=5, text="+", font=("Century Gothic", 16), command=add, bg="#f5b042")
btn1.place(x=30, y=150)
btn2 = Button(win, width=5, text="-", font=("Century Gothic", 16), command=sub, bg="#f5b042")
btn2.place(x=110, y=150)
btn3 = Button(win, width=5, text="x", font=("Century Gothic", 16), command=multiply, bg="#f5b042")
btn3.place(x=190, y=150)
btn4 = Button(win, width=5, text="÷", font=("Century Gothic", 16), command=divide, bg="#f5b042")
btn4.place(x=270, y=150)
btn5 = Button(win, width=5, text="//", font=("Century Gothic", 16), command=floor, bg="#f5b042")
btn5.place(x=350, y=150)
btn6 = Button(win, width=5, text="^", font=("Century Gothic", 16), command=power, bg="#f5b042")
btn6.place(x=430, y=150)
btn7 = Button(win, width=5, text="%", font=("Century Gothic", 16), command=modulo, bg="#f5b042")
btn7.place(x=510, y=150)
win.title("Python Calculator")
win.geometry("600x225+650+280")
win.config(bg="#123740")
win.mainloop()